/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.FirefoxInitializer;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import modal.Rates;
import modal.TableData;

import org.apache.poi.ss.usermodel.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;

/**
 *
 * @author dhanushka
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    boolean eudusd_price = true;
    boolean eudusd_short = true;
    boolean eudusd_intrest = true;

    boolean gbpusd_price = true;
    boolean gbpusd_short = true;
    boolean gbpusd_intrest = true;

    boolean usdjpy_price = true;
    boolean usdjpy_short = true;
    boolean usdjpy_intrest = true;

    boolean usdcad_price = true;
    boolean usdcad_short = true;
    boolean usdcad_intrest = true;

    boolean audusd_price = true;
    boolean audusd_short = true;
    boolean audusd_intrest = true;

    boolean nzdusd_price = true;
    boolean nzdusd_short = true;
    boolean nzdusd_intrest = true;

    boolean sp500_price = true;
    boolean sp500_short = true;
    boolean sp500_intrest = true;

    boolean us30_price = true;
    boolean us30_short = true;
    boolean us30_intrest = true;

    boolean bitcoin_price = true;
    boolean bitcoin_short = true;
    boolean bitcoin_intrest = true;

    boolean ethereum_price = true;
    boolean ethereum_short = true;
    boolean ethereum_intrest = true;

    static int interval = 10;
    FirefoxDriver innerDriver;

    String location = "";

    public Main() {
        initComponents();
        setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        start.setEnabled(false);
        open_sheet.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JSeparator();
        jToggleButton13 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        start = new javax.swing.JButton();
        open_sheet = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Daily FX IG Client Sentiment Data Scraper");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EUR/USD");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Price", "Short", "Interest", "Price", "Short", "Interest", "Price", "Short", "Interest", "Price", "Short", "Interest", "Price", "Short", "Interest", "Price", "Short", "Interest", "Price", "Short", "Interest", "Price", "Short", "Interest", "Price", "Short", "Interest", "Price", "Short", "Interest"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jToggleButton1.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton1.setForeground(java.awt.Color.green);
        jToggleButton1.setText("ON");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        jToggleButton4.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton4.setForeground(java.awt.Color.green);
        jToggleButton4.setText("ON");
        jToggleButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseClicked(evt);
            }
        });

        jToggleButton5.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton5.setForeground(java.awt.Color.green);
        jToggleButton5.setText("ON");
        jToggleButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton5MouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("GBP/USD");

        jToggleButton2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton2.setForeground(java.awt.Color.green);
        jToggleButton2.setText("ON");
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });

        jToggleButton6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton6.setForeground(java.awt.Color.green);
        jToggleButton6.setText("ON");
        jToggleButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton6MouseClicked(evt);
            }
        });

        jToggleButton7.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton7.setForeground(java.awt.Color.green);
        jToggleButton7.setText("ON");
        jToggleButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton7MouseClicked(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("USDJPY");

        jToggleButton3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton3.setForeground(java.awt.Color.green);
        jToggleButton3.setText("ON");
        jToggleButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
        });

        jToggleButton8.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton8.setForeground(java.awt.Color.green);
        jToggleButton8.setText("ON");
        jToggleButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });

        jToggleButton9.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton9.setForeground(java.awt.Color.green);
        jToggleButton9.setText("ON");
        jToggleButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton9MouseClicked(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 153, 153));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("USDCAD");

        jToggleButton10.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton10.setForeground(java.awt.Color.green);
        jToggleButton10.setText("ON");
        jToggleButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton10MouseClicked(evt);
            }
        });

        jToggleButton11.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton11.setForeground(java.awt.Color.green);
        jToggleButton11.setText("ON");
        jToggleButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton11MouseClicked(evt);
            }
        });

        jToggleButton12.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton12.setForeground(java.awt.Color.green);
        jToggleButton12.setText("ON");
        jToggleButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton12MouseClicked(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 153, 153));

        jToggleButton13.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton13.setForeground(java.awt.Color.green);
        jToggleButton13.setText("ON");
        jToggleButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton13MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("AUDUSD");

        jToggleButton14.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton14.setForeground(java.awt.Color.green);
        jToggleButton14.setText("ON");
        jToggleButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton14MouseClicked(evt);
            }
        });

        jToggleButton15.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton15.setForeground(java.awt.Color.green);
        jToggleButton15.setText("ON");
        jToggleButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton15MouseClicked(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 153, 153));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("NZDUSD");

        jToggleButton16.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton16.setForeground(java.awt.Color.green);
        jToggleButton16.setText("ON");
        jToggleButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton16MouseClicked(evt);
            }
        });

        jToggleButton17.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton17.setForeground(java.awt.Color.green);
        jToggleButton17.setText("ON");
        jToggleButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton17MouseClicked(evt);
            }
        });

        jToggleButton18.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton18.setForeground(java.awt.Color.green);
        jToggleButton18.setText("ON");
        jToggleButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton18MouseClicked(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(0, 153, 153));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SP500");

        jToggleButton19.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton19.setForeground(java.awt.Color.green);
        jToggleButton19.setText("ON");
        jToggleButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton19MouseClicked(evt);
            }
        });

        jToggleButton20.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton20.setForeground(java.awt.Color.green);
        jToggleButton20.setText("ON");
        jToggleButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton20MouseClicked(evt);
            }
        });

        jToggleButton21.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton21.setForeground(java.awt.Color.green);
        jToggleButton21.setText("ON");
        jToggleButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton21MouseClicked(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(0, 153, 153));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("US30 Wall Street");

        jToggleButton22.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton22.setForeground(java.awt.Color.green);
        jToggleButton22.setText("ON");
        jToggleButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton22MouseClicked(evt);
            }
        });

        jToggleButton23.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton23.setForeground(java.awt.Color.green);
        jToggleButton23.setText("ON");
        jToggleButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton23MouseClicked(evt);
            }
        });

        jToggleButton24.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton24.setForeground(java.awt.Color.green);
        jToggleButton24.setText("ON");
        jToggleButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton24MouseClicked(evt);
            }
        });

        jSeparator8.setForeground(new java.awt.Color(0, 153, 153));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Bitcoin");

        jToggleButton25.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton25.setForeground(java.awt.Color.green);
        jToggleButton25.setText("ON");
        jToggleButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton25MouseClicked(evt);
            }
        });

        jToggleButton26.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton26.setForeground(java.awt.Color.green);
        jToggleButton26.setText("ON");
        jToggleButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton26MouseClicked(evt);
            }
        });

        jToggleButton27.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton27.setForeground(java.awt.Color.green);
        jToggleButton27.setText("ON");
        jToggleButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton27MouseClicked(evt);
            }
        });

        jSeparator9.setForeground(new java.awt.Color(0, 153, 153));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Ethereum");

        jToggleButton28.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton28.setForeground(java.awt.Color.green);
        jToggleButton28.setText("ON");
        jToggleButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton28MouseClicked(evt);
            }
        });

        jToggleButton29.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton29.setForeground(java.awt.Color.green);
        jToggleButton29.setText("ON");
        jToggleButton29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton29MouseClicked(evt);
            }
        });

        jToggleButton30.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jToggleButton30.setForeground(java.awt.Color.green);
        jToggleButton30.setText("ON");
        jToggleButton30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton30MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2537, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jToggleButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jToggleButton25)
                                    .addComponent(jToggleButton27)
                                    .addComponent(jToggleButton26))
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jToggleButton28)
                                    .addComponent(jToggleButton30)
                                    .addComponent(jToggleButton29))
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jToggleButton22)
                                    .addComponent(jToggleButton24)
                                    .addComponent(jToggleButton23))
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(6, 6, 6)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jToggleButton16)
                                .addComponent(jToggleButton17)
                                .addComponent(jToggleButton18))
                            .addGap(2, 2, 2)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton13)
                            .addComponent(jToggleButton14)
                            .addComponent(jToggleButton15))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton10)
                            .addComponent(jToggleButton11)
                            .addComponent(jToggleButton12))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton3)
                            .addComponent(jToggleButton8)
                            .addComponent(jToggleButton9))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton2)
                            .addComponent(jToggleButton6)
                            .addComponent(jToggleButton7))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton1)
                            .addComponent(jToggleButton4)
                            .addComponent(jToggleButton5))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton19)
                            .addComponent(jToggleButton21)
                            .addComponent(jToggleButton20))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jTextField1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("10");
        jTextField1.setToolTipText("minutes");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Update Rate");

        jButton2.setText("SET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        start.setText("START");
        start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        open_sheet.setText("Open Sheet");
        open_sheet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        open_sheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_sheetActionPerformed(evt);
            }
        });

        jButton4.setText("Location");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(start)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(open_sheet)))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton4, open_sheet, start});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(start)
                    .addComponent(open_sheet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jTextField1});

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("AKVASOFT");

        jLabel14.setText("solutions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(155, 155, 155))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1636, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        start.setEnabled(false);
        jButton4.setEnabled(false);

        try {
            createXlsFile();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.out.println("INTERVAL " + interval);
        System.setProperty("webdriver.gecko.driver", "/var/lib/tomcat8/geckodriver");
        FirefoxOptions options2 = new FirefoxOptions();
        options2.setHeadless(true);
        innerDriver = new FirefoxDriver(options2);

        new Thread(() -> {
            FirefoxDriver innerDriver;
            System.setProperty("webdriver.gecko.driver", "/var/lib/tomcat8/geckodriver");
            FirefoxOptions options = new FirefoxOptions();
            options.setHeadless(true);
            while (true) {
                try {

                    scrapeRates(new FirefoxDriver(options));
                    Thread.sleep(interval * 60000);

                } catch (InterruptedException e) {
                    e.printStackTrace();
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InvalidFormatException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }).start();

    }//GEN-LAST:event_startActionPerformed

    public void createXlsFile() throws IOException {
        try {
            new FileInputStream(location + "/forex.xlsx");
        } catch (FileNotFoundException e) {
            new File("/var/lib/tomcat8/forex").mkdir();
            Workbook workbook = new XSSFWorkbook();

            CreationHelper createHelper = workbook.getCreationHelper();
            Sheet sheet = workbook.createSheet("forex");
            Font headerFont = workbook.createFont();
            headerFont.setBold(true);
            headerFont.setFontHeightInPoints((short) 14);
            headerFont.setColor(IndexedColors.RED.getIndex());

            Font headerFont2 = workbook.createFont();
            headerFont2.setBold(true);
            headerFont2.setFontHeightInPoints((short) 14);
            headerFont2.setColor(IndexedColors.BLACK.getIndex());

            CellStyle headerCellStyle = workbook.createCellStyle();
            headerCellStyle.setFont(headerFont);

            CellStyle headerCellStyle2 = workbook.createCellStyle();
            headerCellStyle2.setFont(headerFont2);

            Row headerRow = sheet.createRow(1);
            Row headerRow2 = sheet.createRow(0);
//            
            ArrayList<String> list = new ArrayList();
            ArrayList<String> list2 = new ArrayList();

            list2.add("");
            list2.add("EUR/USD");
            list2.add("");

            list2.add("");
            list2.add("GBP/USD");
            list2.add("");

            list2.add("");
            list2.add("USDJPY");
            list2.add("");

            list2.add("");
            list2.add("USDCAD");
            list2.add("");

            list2.add("");
            list2.add("AUDUSD");
            list2.add("");

            list2.add("");
            list2.add("NZDUSD");
            list2.add("");

            list2.add("");
            list2.add("SP500");
            list2.add("");

            list2.add("");
            list2.add("US30 WALL STREET");
            list2.add("");

            list2.add("");
            list2.add("BITCOIN");
            list2.add("");

            list2.add("");
            list2.add("ETHEREUM");
            list2.add("");

            for (int i = 0; i < list2.size(); i++) {
                Cell cell = headerRow2.createCell(i);
                cell.setCellValue(list2.get(i));
                cell.setCellStyle(headerCellStyle2);
            }
            CellStyle dateCellStyle2 = workbook.createCellStyle();
            dateCellStyle2.setDataFormat(createHelper.createDataFormat().getFormat("dd/MM/yyyy"));

            list.add("Date");
            for (int i = 0; i < 10; i++) {
                list.add("Price");
                list.add("Short");
                list.add("Intrest");
            }

            for (int i = 0; i < list.size(); i++) {
                Cell cell = headerRow.createCell(i);
                cell.setCellValue(list.get(i));
                cell.setCellStyle(headerCellStyle);
            }

            CellStyle dateCellStyle = workbook.createCellStyle();
            dateCellStyle.setDataFormat(createHelper.createDataFormat().getFormat("dd/MM/yyyy"));
            sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, 2));
            FileOutputStream fileOut = new FileOutputStream(location + "/forex.xlsx");
            workbook.write(fileOut);
            fileOut.close();
            System.out.println("Excel Created");
        }

    }

    private void appendRow(TableData data) throws IOException, InvalidFormatException {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = new Date();

        try {

            Workbook wb3 = WorkbookFactory.create(new FileInputStream(location + "/forex.xlsx"));
            Sheet sh = wb3.getSheet("forex");
            int rows = sh.getLastRowNum();
//            sh.shiftRows(2, sh.getLastRowNum(), 1, true, true);
            Row row = sh.createRow(++rows);

            row.createCell(0).setCellValue(formatter.format(date));

            row.createCell(1).setCellValue(data.getEURUSD().getAsk());
            row.createCell(2).setCellValue(data.getEURUSD().getShortValue());
            row.createCell(3).setCellValue(data.getEURUSD().getChangeOpenInterest());

            row.createCell(4).setCellValue(data.getGBPUSD().getAsk());
            row.createCell(5).setCellValue(data.getGBPUSD().getShortValue());
            row.createCell(6).setCellValue(data.getGBPUSD().getChangeOpenInterest());

            row.createCell(7).setCellValue(data.getUSDJPY().getAsk());
            row.createCell(8).setCellValue(data.getUSDJPY().getShortValue());
            row.createCell(9).setCellValue(data.getUSDJPY().getChangeOpenInterest());

            row.createCell(10).setCellValue(data.getUSDCAD().getAsk());
            row.createCell(11).setCellValue(data.getUSDCAD().getShortValue());
            row.createCell(12).setCellValue(data.getUSDCAD().getChangeOpenInterest());

            row.createCell(13).setCellValue(data.getAUDUSD().getAsk());
            row.createCell(14).setCellValue(data.getAUDUSD().getShortValue());
            row.createCell(15).setCellValue(data.getAUDUSD().getChangeOpenInterest());

            row.createCell(16).setCellValue(data.getNZDUSD().getAsk());
            row.createCell(17).setCellValue(data.getNZDUSD().getShortValue());
            row.createCell(18).setCellValue(data.getNZDUSD().getChangeOpenInterest());

            row.createCell(19).setCellValue(data.getSP500().getAsk());
            row.createCell(20).setCellValue(data.getSP500().getShortValue());
            row.createCell(21).setCellValue(data.getSP500().getChangeOpenInterest());

            row.createCell(22).setCellValue(data.getUS30WallSttreet().getAsk());
            row.createCell(23).setCellValue(data.getUS30WallSttreet().getShortValue());
            row.createCell(24).setCellValue(data.getUS30WallSttreet().getChangeOpenInterest());

            row.createCell(25).setCellValue(data.getBitcoin().getAsk());
            row.createCell(26).setCellValue(data.getBitcoin().getShortValue());
            row.createCell(27).setCellValue(data.getBitcoin().getChangeOpenInterest());

            row.createCell(28).setCellValue(data.getEthereum().getAsk());
            row.createCell(29).setCellValue(data.getEthereum().getShortValue());
            row.createCell(30).setCellValue(data.getEthereum().getChangeOpenInterest());

            FileOutputStream fileOut = new FileOutputStream(location + "/forex.xlsx");
            wb3.write(fileOut);
            fileOut.close();
            System.out.println("excel updated.");

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        eudusd_price = disableColumns(jToggleButton1);
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseClicked
        eudusd_short = disableColumns(jToggleButton4);
    }//GEN-LAST:event_jToggleButton4MouseClicked

    private void jToggleButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton5MouseClicked
        eudusd_intrest = disableColumns(jToggleButton5);
    }//GEN-LAST:event_jToggleButton5MouseClicked

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        gbpusd_price = disableColumns(jToggleButton2);
    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void jToggleButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton6MouseClicked
        gbpusd_short = disableColumns(jToggleButton6);
    }//GEN-LAST:event_jToggleButton6MouseClicked

    private void jToggleButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton7MouseClicked
        gbpusd_intrest = disableColumns(jToggleButton7);
    }//GEN-LAST:event_jToggleButton7MouseClicked

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked
        usdjpy_price = disableColumns(jToggleButton3);
    }//GEN-LAST:event_jToggleButton3MouseClicked

    private void jToggleButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton8MouseClicked
        usdjpy_short = disableColumns(jToggleButton8);
    }//GEN-LAST:event_jToggleButton8MouseClicked

    private void jToggleButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton9MouseClicked
        usdjpy_intrest = disableColumns(jToggleButton9);
    }//GEN-LAST:event_jToggleButton9MouseClicked

    private void jToggleButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton10MouseClicked
        usdcad_price = disableColumns(jToggleButton10);
    }//GEN-LAST:event_jToggleButton10MouseClicked

    private void jToggleButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton11MouseClicked
        usdcad_short = disableColumns(jToggleButton11);
    }//GEN-LAST:event_jToggleButton11MouseClicked

    private void jToggleButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton12MouseClicked
        usdcad_intrest = disableColumns(jToggleButton12);
    }//GEN-LAST:event_jToggleButton12MouseClicked

    private void jToggleButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton13MouseClicked
        audusd_price = disableColumns(jToggleButton13);
    }//GEN-LAST:event_jToggleButton13MouseClicked

    private void jToggleButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton14MouseClicked
        audusd_short = disableColumns(jToggleButton14);
    }//GEN-LAST:event_jToggleButton14MouseClicked

    private void jToggleButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton15MouseClicked
        audusd_intrest = disableColumns(jToggleButton15);
    }//GEN-LAST:event_jToggleButton15MouseClicked

    private void jToggleButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton16MouseClicked
        nzdusd_price = disableColumns(jToggleButton16);
    }//GEN-LAST:event_jToggleButton16MouseClicked

    private void jToggleButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton17MouseClicked
        nzdusd_short = disableColumns(jToggleButton17);
    }//GEN-LAST:event_jToggleButton17MouseClicked

    private void jToggleButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton18MouseClicked
        nzdusd_intrest = disableColumns(jToggleButton18);
    }//GEN-LAST:event_jToggleButton18MouseClicked

    private void jToggleButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton19MouseClicked
        sp500_price = disableColumns(jToggleButton19);
    }//GEN-LAST:event_jToggleButton19MouseClicked

    private void jToggleButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton21MouseClicked
        sp500_short = disableColumns(jToggleButton21);
    }//GEN-LAST:event_jToggleButton21MouseClicked

    private void jToggleButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton20MouseClicked
        sp500_intrest = disableColumns(jToggleButton20);
    }//GEN-LAST:event_jToggleButton20MouseClicked

    private void jToggleButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton22MouseClicked
        us30_price = disableColumns(jToggleButton22);
    }//GEN-LAST:event_jToggleButton22MouseClicked

    private void jToggleButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton24MouseClicked
        us30_short = disableColumns(jToggleButton24);
    }//GEN-LAST:event_jToggleButton24MouseClicked

    private void jToggleButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton23MouseClicked
        us30_intrest = disableColumns(jToggleButton23);
    }//GEN-LAST:event_jToggleButton23MouseClicked

    private void jToggleButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton25MouseClicked
        bitcoin_price = disableColumns(jToggleButton25);
    }//GEN-LAST:event_jToggleButton25MouseClicked

    private void jToggleButton27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton27MouseClicked
        bitcoin_short = disableColumns(jToggleButton27);
    }//GEN-LAST:event_jToggleButton27MouseClicked

    private void jToggleButton26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton26MouseClicked
        bitcoin_intrest = disableColumns(jToggleButton26);
    }//GEN-LAST:event_jToggleButton26MouseClicked

    private void jToggleButton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton28MouseClicked
        ethereum_price = disableColumns(jToggleButton28);
    }//GEN-LAST:event_jToggleButton28MouseClicked

    private void jToggleButton30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton30MouseClicked
        ethereum_short = disableColumns(jToggleButton30);
    }//GEN-LAST:event_jToggleButton30MouseClicked

    private void jToggleButton29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton29MouseClicked
        ethereum_intrest = disableColumns(jToggleButton29);
    }//GEN-LAST:event_jToggleButton29MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int min = Integer.parseInt(jTextField1.getText());
        interval = min;
        System.out.println(interval + " set");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void open_sheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_sheetActionPerformed
        try {
            File file = new File(location + "/forex.xlsx");
            Desktop.getDesktop().open(file);

        } catch (IOException ex) {
            Logger.getLogger(Main.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_open_sheetActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser f = new JFileChooser();
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        f.showSaveDialog(null);
        System.out.println(f.getSelectedFile().getAbsolutePath());
        location = f.getSelectedFile().getAbsolutePath();
        start.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void scrapeRates(FirefoxDriver driver) throws InterruptedException, IOException, InvalidFormatException {
        Rates r = null;
        TableData data = new TableData();
        JavascriptExecutor js = (JavascriptExecutor) driver;

        driver.get("https://www.dailyfx.com/forex-rates?ref=TopRates");

        WebElement table = driver.findElementByXPath("/html/body/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/table");
        List<WebElement> trs = table.findElement(By.tagName("tbody")).findElements(By.xpath("./*"));

        for (WebElement tr : trs) {
            if (tr.findElements(By.xpath("./*")).get(0).getAttribute("innerText").equalsIgnoreCase("EURUSD")
                    || tr.findElements(By.xpath("./*")).get(0).getAttribute("innerText").equalsIgnoreCase("GBPUSD")
                    || tr.findElements(By.xpath("./*")).get(0).getAttribute("innerText").equalsIgnoreCase("USDJPY")
                    || tr.findElements(By.xpath("./*")).get(0).getAttribute("innerText").equalsIgnoreCase("USDCAD")
                    || tr.findElements(By.xpath("./*")).get(0).getAttribute("innerText").equalsIgnoreCase("AUDUSD")
                    || tr.findElements(By.xpath("./*")).get(0).getAttribute("innerText").equalsIgnoreCase("NZDUSD")
                    || tr.findElements(By.xpath("./*")).get(0).getAttribute("innerText").equalsIgnoreCase("Ethereum")
                    || tr.findElements(By.xpath("./*")).get(0).getAttribute("innerText").equalsIgnoreCase("Bitcoin")) {

                System.out.println(tr.findElements(By.xpath("./*")).get(1).findElement(By.tagName("span")).getAttribute("data-value") + "+=======================");
                System.out.println(tr.findElements(By.xpath("./*")).get(2).findElement(By.tagName("span")).getAttribute("data-value") + "+=======================");

                r = new Rates();
                r.setSymbol(tr.findElements(By.xpath("./*")).get(0).getAttribute("innerText"));
                r.setBid(tr.findElements(By.xpath("./*")).get(1).findElement(By.tagName("span")).getAttribute("data-value"));
                r.setAsk(tr.findElements(By.xpath("./*")).get(2).findElement(By.tagName("span")).getAttribute("data-value"));

                if (r.getSymbol().equalsIgnoreCase("EURUSD")) {
                    data.setEURUSD(getInnerData(r, tr.findElements(By.xpath("./*")).get(0).findElement(By.tagName("span")).findElement(By.tagName("a")).getAttribute("href")));
                } else if (r.getSymbol().equalsIgnoreCase("GBPUSD")) {
                    data.setGBPUSD(getInnerData(r, tr.findElements(By.xpath("./*")).get(0).findElement(By.tagName("span")).findElement(By.tagName("a")).getAttribute("href")));
                } else if (r.getSymbol().equalsIgnoreCase("USDJPY")) {
                    data.setUSDJPY(getInnerData(r, tr.findElements(By.xpath("./*")).get(0).findElement(By.tagName("span")).findElement(By.tagName("a")).getAttribute("href")));
                } else if (r.getSymbol().equalsIgnoreCase("USDCAD")) {
                    data.setUSDCAD(getInnerData(r, tr.findElements(By.xpath("./*")).get(0).findElement(By.tagName("span")).findElement(By.tagName("a")).getAttribute("href")));
                } else if (r.getSymbol().equalsIgnoreCase("AUDUSD")) {
                    data.setAUDUSD(getInnerData(r, tr.findElements(By.xpath("./*")).get(0).findElement(By.tagName("span")).findElement(By.tagName("a")).getAttribute("href")));
                } else if (r.getSymbol().equalsIgnoreCase("NZDUSD")) {
                    data.setNZDUSD(getInnerData(r, tr.findElements(By.xpath("./*")).get(0).findElement(By.tagName("span")).findElement(By.tagName("a")).getAttribute("href")));
                } else if (r.getSymbol().equalsIgnoreCase("Ethereum")) {
                    data.setEthereum(getInnerData(r, tr.findElements(By.xpath("./*")).get(0).findElement(By.tagName("span")).findElement(By.tagName("a")).getAttribute("href")));
                } else if (r.getSymbol().equalsIgnoreCase("Bitcoin")) {
                    data.setBitcoin(getInnerData(r, tr.findElements(By.xpath("./*")).get(0).findElement(By.tagName("span")).findElement(By.tagName("a")).getAttribute("href")));
                }

            }
        }

        WebElement Indices = driver.findElementByXPath("/html/body/div[1]/div[2]/div[2]/div[1]/div[3]/div[2]/table[2]/tbody");
        List<WebElement> trs2 = Indices.findElements(By.xpath("./*"));
        for (WebElement tr : trs2) {

            // US 500 for SP 500
            // Wall Street for US 30 Wall Street
            if (tr.findElements(By.xpath("./*")).get(0).getAttribute("innerText").equalsIgnoreCase("Wall Street")
                    || tr.findElements(By.xpath("./*")).get(0).getAttribute("innerText").equalsIgnoreCase("US 500")) {

                r = new Rates();
                r.setSymbol(tr.findElements(By.xpath("./*")).get(0).getAttribute("innerText"));
                r.setBid(tr.findElements(By.xpath("./*")).get(1).findElement(By.tagName("span")).getAttribute("data-value"));
                r.setAsk(tr.findElements(By.xpath("./*")).get(2).findElement(By.tagName("span")).getAttribute("data-value"));

                if (r.getSymbol().equalsIgnoreCase("Wall Street")) {
                    data.setUS30WallSttreet(getInnerData(r, tr.findElements(By.xpath("./*")).get(0).findElement(By.tagName("span")).findElement(By.tagName("a")).getAttribute("href")));
                } else if (r.getSymbol().equalsIgnoreCase("US 500")) {
                    data.setSP500(getInnerData(r, tr.findElements(By.xpath("./*")).get(0).findElement(By.tagName("span")).findElement(By.tagName("a")).getAttribute("href")));
                }

            }
        }
        setData(data);
        driver.close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JButton open_sheet;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables

    private void setData(TableData data) throws IOException, InvalidFormatException {
        System.out.println("setting data");

        data = checkDisable(data);
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = new Date();

        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            jTable1.setModel(model);
            model.addRow(new Object[]{formatter.format(date),
                data.getEURUSD().getAsk(), data.getEURUSD().getShortValue(), data.getEURUSD().getChangeOpenInterest(),
                data.getGBPUSD().getAsk(), data.getGBPUSD().getShortValue(), data.getGBPUSD().getChangeOpenInterest(),
                data.getUSDJPY().getAsk(), data.getUSDJPY().getShortValue(), data.getUSDJPY().getChangeOpenInterest(),
                data.getUSDCAD().getAsk(), data.getUSDCAD().getShortValue(), data.getUSDCAD().getChangeOpenInterest(),
                data.getAUDUSD().getAsk(), data.getAUDUSD().getShortValue(), data.getAUDUSD().getChangeOpenInterest(),
                data.getNZDUSD().getAsk(), data.getNZDUSD().getShortValue(), data.getNZDUSD().getChangeOpenInterest(),
                data.getSP500().getAsk(), data.getSP500().getShortValue(), data.getSP500().getChangeOpenInterest(),
                data.getUS30WallSttreet().getAsk(), data.getUS30WallSttreet().getShortValue(), data.getUS30WallSttreet().getChangeOpenInterest(),
                data.getBitcoin().getAsk(), data.getBitcoin().getShortValue(), data.getBitcoin().getChangeOpenInterest(),
                data.getEthereum().getAsk(), data.getEthereum().getShortValue(), data.getEthereum().getChangeOpenInterest(),}
            );
        } catch (NullPointerException e) {
            e.printStackTrace();
        }

        appendRow(data);
        open_sheet.setEnabled(true);
    }

    private Rates getInnerData(Rates r, String attribute) throws InterruptedException {

        innerDriver.get(attribute);
        Thread.sleep(5000);

        WebElement sentiment = null;
        String shortValue = null;
        String interest = null;

        sentiment = innerDriver.findElementByCssSelector(".margin-bottom-40 > div:nth-child(1) > div:nth-child(3)");
        shortValue = sentiment.findElements(By.xpath("./*")).get(2).getAttribute("innerText");
        interest = sentiment.findElements(By.xpath("./*")).get(3).getAttribute("innerText");

        System.out.println(shortValue + "=======");
        System.out.println(interest + "=======");

        r.setShortValue(shortValue.split("\n")[1]);
        r.setChangeOpenInterest(interest.split("\n")[1]);
        System.out.println(r.getSymbol() + " collected");
        return r;
    }

    private boolean disableColumns(JToggleButton button) {
        String text = button.getText();
        if (text.equalsIgnoreCase("ON")) {
            button.setText("OFF");
            button.setForeground(Color.red);
            return false;
        } else {
            button.setText("ON");
            button.setForeground(Color.green);
            return true;
        }
    }

    private TableData checkDisable(TableData data) {
        if (!eudusd_price) {
            data.getEURUSD().setAsk("-");
            data.getEURUSD().setBid("-");
        }
        if (!eudusd_short) {
            data.getEURUSD().setShortValue("-");
        }
        if (!eudusd_intrest) {
            data.getEURUSD().setChangeOpenInterest("-");
        }

        if (!gbpusd_price) {
            data.getGBPUSD().setAsk("-");
            data.getGBPUSD().setBid("-");
        }
        if (!gbpusd_short) {
            data.getGBPUSD().setShortValue("-");
        }
        if (!gbpusd_intrest) {
            data.getGBPUSD().setChangeOpenInterest("-");
        }

        ///
        if (!usdjpy_price) {
            data.getUSDJPY().setAsk("-");
            data.getUSDJPY().setBid("-");
        }
        if (!usdjpy_short) {
            data.getUSDJPY().setShortValue("-");
        }
        if (!usdjpy_intrest) {
            data.getUSDJPY().setChangeOpenInterest("-");
        }

        //
        if (!usdcad_price) {
            data.getUSDCAD().setAsk("-");
            data.getUSDCAD().setBid("-");
        }
        if (!usdcad_short) {
            data.getUSDCAD().setShortValue("-");
        }
        if (!usdcad_intrest) {
            data.getUSDCAD().setChangeOpenInterest("-");
        }

        //
        if (!audusd_price) {
            data.getAUDUSD().setAsk("-");
            data.getAUDUSD().setBid("-");
        }
        if (!audusd_short) {
            data.getAUDUSD().setShortValue("-");
        }
        if (!audusd_intrest) {
            data.getAUDUSD().setChangeOpenInterest("-");
        }

        //
        if (!nzdusd_price) {
            data.getNZDUSD().setAsk("-");
            data.getNZDUSD().setBid("-");
        }
        if (!nzdusd_short) {
            data.getNZDUSD().setShortValue("-");
        }
        if (!nzdusd_intrest) {
            data.getNZDUSD().setChangeOpenInterest("-");
        }

        //
        if (!sp500_price) {
            data.getSP500().setAsk("-");
            data.getSP500().setBid("-");
        }
        if (!sp500_short) {
            data.getSP500().setShortValue("-");
        }
        if (!sp500_intrest) {
            data.getSP500().setChangeOpenInterest("-");
        }

        //
        if (!us30_price) {
            data.getUS30WallSttreet().setAsk("-");
            data.getUS30WallSttreet().setBid("-");
        }
        if (!us30_short) {
            data.getUS30WallSttreet().setShortValue("-");
        }
        if (!us30_intrest) {
            data.getUS30WallSttreet().setChangeOpenInterest("-");
        }

        //
        if (!bitcoin_price) {
            data.getBitcoin().setAsk("-");
            data.getBitcoin().setBid("-");
        }
        if (!bitcoin_short) {
            data.getBitcoin().setShortValue("-");
        }
        if (!bitcoin_intrest) {
            data.getBitcoin().setChangeOpenInterest("-");
        }

        //
        if (!ethereum_price) {
            data.getEthereum().setAsk("-");
            data.getEthereum().setBid("-");
        }
        if (!ethereum_short) {
            data.getEthereum().setShortValue("-");
        }
        if (!ethereum_intrest) {
            data.getEthereum().setChangeOpenInterest("-");
        }

        return data;
    }

}
